package com.example.kotlinroomdatabase.data

import androidx.room.Entity
import androidx.room.PrimaryKey

// User Entity represents a table within the database.
@Entity(tableName = "user_table")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val firstName: String,
    val lastName: String,
    val age: Int
)